### ISSUE TITLE
Bitmax deserialize error message with .NET core 5

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#1]
Method: PlaceMarginOrder. 
Repeat: Make unsuccess order , example size sell btc = 100000
Clear .net core 5 project.

"Deserialize JsonReaderException: Unexpected character encountered while parsing value: {. Path 'info', line 1, position 215., Path: info, LineNumber: 1, LinePosition: 215"

![image](https://user-images.githubusercontent.com/61819835/104123907-cad63800-535e-11eb-91ec-0d036f93f787.png)

**Comment by burakoner** [comment]
BitMax Api is very complicated. Because same api endpoints returns different data structures always. This time api returns an object of a different model in error response. I fixed this error in https://github.com/burakoner/BitMax.Net/commit/233e266eee293930668911552a5a838d67e2654f commit. I uploaded new package to nuget as well.

I tried as possible as much trials on BitMax.Net. If you got different errors please let me know to fix it.

Thank you for your feedback. Have a nice day.
